-- Music cues generated by Lyria 3 for background music
create table if not exists public.music_cues (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  asset_id uuid not null references public.media_assets(id) on delete cascade,
  job_id uuid references public.analysis_jobs(id) on delete set null,
  music_segment_id text not null,
  source_start double precision not null,
  source_end double precision not null,
  duration_seconds double precision not null,
  mood text not null,
  energy text not null,
  genre_hints jsonb not null default '[]'::jsonb,
  storage_path text,
  status text not null default 'suggested',
  volume_db double precision not null default -18,
  fade_in_seconds double precision not null default 1.0,
  fade_out_seconds double precision not null default 1.5,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists music_cues_project_id_idx on public.music_cues(project_id);
create index if not exists music_cues_asset_id_idx on public.music_cues(asset_id);

drop trigger if exists set_music_cues_updated_at on public.music_cues;
create trigger set_music_cues_updated_at
before update on public.music_cues
for each row
execute function public.set_updated_at();

alter table public.music_cues enable row level security;

drop policy if exists "users can view own project music cues" on public.music_cues;
create policy "users can view own project music cues"
on public.music_cues
for select
using (
  project_id in (select id from public.projects where user_id = auth.uid())
);

drop policy if exists "users can manage own project music cues" on public.music_cues;
create policy "users can manage own project music cues"
on public.music_cues
for all
using (
  project_id in (select id from public.projects where user_id = auth.uid())
)
with check (
  project_id in (select id from public.projects where user_id = auth.uid())
);

-- Music storage bucket (private)
insert into storage.buckets (id, name, public)
values ('music', 'music', false)
on conflict (id) do nothing;

-- Service role can manage all music files (used by worker)
drop policy if exists "service role can manage music" on storage.objects;
create policy "service role can manage music"
on storage.objects
for all
using (bucket_id = 'music')
with check (bucket_id = 'music');
